### PR TITLE
Changes by running 'make fmt'

### PR DESCRIPTION
**Pull request by davidcassany**
Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

**Comment by davidcassany** [comment]
I thought that the lint check would catch these little leftovers, it seams it doesn't 🤷🏽‍♂️
I guess it does not return an error if some changes are applied.

**Review by Itxaka — APPROVED** [review]
Weird, I swear I thought I added this as part of make lint :/

**Comment by davidcassany** [comment]
> Weird, I swear I thought I added this as part of make lint :/

I believe it is just executed, applies changes in the local checkout and it doesn't error out.

**Comment by Itxaka** [comment]
I don't understand codecov. How is this supposed to increase coverage???

**Pull request merged**
