### PR TITLE
Add global flag for debug level

### LINKED ISSUE #37: Enable configuration of loglevel
Currently there is no way of configuring the loglevel which is kind of bad, we have logging all around with debug level but there is no way of accessing it if something starts to fail.

we should have it as part of the runConfig so its loaded from files/env var and reconfigures the logger passed to the Runconfig on instance creation/struct creation.

### PR DESCRIPTION
**Pull request by Itxaka**
Fixes #37 

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
LGTM

**Comment by Itxaka** [comment]
Gonna add a couple of tests maybe to bring those numbers up :/

Maybe we should just ignore the cmd code from being counted against code coverage, as its kind of absurd to test flags and so on...

**Comment by davidcassany** [comment]
> Maybe we should just ignore the cmd code from being counted against code coverage, as its kind of absurd to test flags and so on...

Yes, it would be nice to be able to customize what is counted and what not in code coverage. I have not investigated it in any way, probably it is possible to add decorators to omit code lines or configure the omission of certain files... I agree sometimes it feels silly trying to test certain execution paths or code portions.

**Comment by Itxaka** [comment]
Unfortunately there is nothing in the standard library to ignore lines...nor there are plans to add anything...

**Pull request merged**
