### PR TITLE
Introduce generic arch flag for build commands

### PR DESCRIPTION
**Pull request by Itxaka**
Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
@davidcassany would something like this work? Or were you thinking something more different?

This is a very simplistic arch implementation, as we only modify the default repos to add the proper ones and allow cross-build of iso (disk was already possible). 

Another implementation could be to add the arch to the repositories, so we could enable/disable them based of the required given arch, like luet does, but that would be more complicated and would require more changes to our whole thing.

**Comment by davidcassany** [comment]
> This is a very simplistic arch implementation, as we only modify the default repos to add the proper ones and allow cross-build of iso (disk was already possible).

Yes this is the major and first step
 
> Another implementation could be to add the arch to the repositories, so we could enable/disable them based of the required given arch, like luet does, but that would be more complicated and would require more changes to our whole thing.

Rather than another implementation, it should be added on top. So it can easily be a second round and also get rid of nested repositories in `build-disk`. I'd do that as a follow up once all other stuff is settled.

**Review by davidcassany — APPROVED** [review]
Looks good to me

**Comment by mudler** [comment]
uhm. weird. after this was merged to master tests started to fail? https://github.com/rancher-sandbox/elemental/runs/6287438234?check_suite_focus=true

**Comment by Itxaka** [comment]
No really, that command test has a weird fetiah for failing randomly, but only on ci

**Comment by Itxaka** [comment]
Just retriggered and now it passed... Probably should open a bug

**Pull request merged**
