### PR TITLE
Full installation from downloaded ISO

### LINKED ISSUE #1054: Review installer `--iso` behavior
At a glance it looks like the current behavior of `--iso` flag in `cos-installer` script is not obvious and rare. This was seen while porting all the installer flags to the elemental-cli. This card is devoted to clarify the desired behavior of this flag and implement it in elemental-cli. This should help to clarify some of the non obvious logic in `CopyRecovery` method: 
https://github.com/rancher-sandbox/elemental-cli/blob/de49930db138d8306be8d3cb869f1abdc1331833/pkg/elemental/elemental.go#L418-L430

IMHO the `--iso` flag should mean:

1. Download ISO
2. Mount ISO
3. Use ISO's system image as Active image
4. Use recovery squashfs image if any or reuse Active as recovery instead.
5. This is all independent of booting from an ISO or not

### PR DESCRIPTION
**Pull request by davidcassany**
Fixes rancher-sandbox/cOS-toolkit#1054

Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

**Comment by davidcassany** [comment]
I manually tested it by downloading the latest cOS release ISO and calling:

```bash
# Create a fresh disk
$ qemu-img create -f raw disk.img 30G
$ sudo losetup -f --show disk.img
$ sudo elemental install --iso cOS-Seed-green-0.8.2-5-gc8e7ede1-x86_64.iso /dev/loop0
$ sudo losetup -d /dev/loop0

# Launch disk
$ qemu-kvm -m 2048 -hda disk.img -bios /usr/share/qemu/ovmf-x86_64.bin
```

**Review by mudler — APPROVED** [review]
Looks good!

**Comment by mudler** [comment]
> I manually tested it by downloading the latest cOS release ISO and calling:
> 
> ```shell
> # Create a fresh disk
> $ qemu-img create -f raw disk.img 30G
> $ sudo losetup -f --show disk.img
> $ sudo elemental install --iso cOS-Seed-green-0.8.2-5-gc8e7ede1-x86_64.iso /dev/loop0
> $ sudo losetup -d /dev/loop0
> 
> # Launch disk
> $ qemu-kvm -m 2048 -hda disk.img -bios /usr/share/qemu/ovmf-x86_64.bin
> ```

This really needs to be documented (very nice!), maybe a comment in the code portion as for now before moving to docs?

**Comment by davidcassany** [comment]
> > I manually tested it by downloading the latest cOS release ISO and calling:
> > ```shell
> > # Create a fresh disk
> > $ qemu-img create -f raw disk.img 30G
> > $ sudo losetup -f --show disk.img
> > $ sudo elemental install --iso cOS-Seed-green-0.8.2-5-gc8e7ede1-x86_64.iso /dev/loop0
> > $ sudo losetup -d /dev/loop0
> > 
> > # Launch disk
> > $ qemu-kvm -m 2048 -hda disk.img -bios /usr/share/qemu/ovmf-x86_64.bin
> > ```
> 
> This really needs to be documented (very nice!), maybe a comment in the code portion as for now before moving to docs?

Yes this should be documented somewhere, gonna think about the possibilities. I think we should also release ISOs not in a tarball, directly release the ISO itself. This way we could use the remote url directly for that purpose.

With the above I also missed something like `--force-mbr` for legacy disk creation (yes, we are at 2022 and hipervisors are still easier to work with MBR 😅) since elemental detected EFI on my host it executed an EFI installation.

**Comment by mudler** [comment]
> > > I manually tested it by downloading the latest cOS release ISO and calling:
> > > ```shell
> > > # Create a fresh disk
> > > $ qemu-img create -f raw disk.img 30G
> > > $ sudo losetup -f --show disk.img
> > > $ sudo elemental install --iso cOS-Seed-green-0.8.2-5-gc8e7ede1-x86_64.iso /dev/loop0
> > > $ sudo losetup -d /dev/loop0
> > > 
> > > # Launch disk
> > > $ qemu-kvm -m 2048 -hda disk.img -bios /usr/share/qemu/ovmf-x86_64.bin
> > > ```
> > 
> > 
> > This really needs to be documented (very nice!), maybe a comment in the code portion as for now before moving to docs?
> 
> Yes this should be documented somewhere, gonna think about the possibilities. I think we should also release ISOs not in a tarball, directly release the ISO itself. This way we could use the remote url directly for that purpose.

for cOS itself wouldn't really matter as ISOS shouldn't be used for installation etc at the end ...  but we can still use os2 ISOS for testing :grin: 

> 
> With the above I also missed something like `--force-mbr` for legacy disk creation (yes, we are at 2022 and hipervisors are still easier to work with MBR sweat_smile) since elemental detected EFI on my host it executed an EFI installation.

:+1:

**Pull request merged**
