### PR TITLE
Set serial tests with ginkgo dsl

### PR DESCRIPTION
**Pull request by Itxaka**
No need to filter ourselves, the nice folks from ginkgo already thougth
of this :)

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
Im thinking that this should be impossible unless we are picking a wrong temp dir. AFAIK /tmp in the runners is mounted from the main disk, which should have around 20/30Gb free. The images are rounded up, yes but that means it should be a maximun of 3 images at the same time which are comprised of:

 - parts: maximum of 2200Mb (fixed image sizes, no matter the content)
 - raw image: 2200Mb as its the contents of the parts
 - Transformed image (azure rounded to 1Mb, gce to 1Gb so a max of 3Gb)
 
That would make the dir contain a max of 8Gb for GCE test, 4,5Gb for azure and 4Gb for simply the raw image.

Maybe things are not being cleaned up instead?

**Comment by Itxaka** [comment]
oh well, just saw @fgiudici PR, its explained in there that it comes from a small /tmp dir (7Gb). Yup, that makes sense, but still we could be aggressive and clean up shit as soon as we are done with it, we would remove several GB. Notice that the raw image tests are slow so running them in serial introduces some time lost on our CI runs.

**Comment by fgiudici** [comment]
> oh well, just saw @fgiudici PR, its explained in there that it comes from a small /tmp dir (7Gb). Yup, that makes sense, but still we could be aggressive and clean up shit as soon as we are done with it, we would remove several GB. Notice that the raw image tests are slow so running them in serial introduces some time lost on our CI runs.

Yep, makes sense. Not a problem for me to get back to full parallel tests... I was just thinking anyway the "casual" contributor wanting to run the "make tests" locally may hit this. But if this slows down too much our CI pipeline that is a no go...

**Comment by fgiudici** [comment]
> No need to filter ourselves, the nice folks from ginkgo already thougth of this :)

Cool! (Tried it locally)

**Review by fgiudici — APPROVED** [review]

**Comment by Itxaka** [comment]
oh shit, we forgot to add the different codecov outputs when splitting the tests so it was reporting a really low coverage :D

**Pull request merged**
