### PR TITLE
Bump grsync wrapper

### LINKED ISSUE #124: Some race conditions in our tests
Looks like our rsync lib sometimes produces race conditions during tests: https://github.com/rancher-sandbox/elemental/runs/5405027256?check_suite_focus=true

### PR DESCRIPTION
**Pull request by davidcassany**
This commit bumps grsync package to fix some race issues that were time to time detected in our unit tests.

The version bump includes zloylos/grsync#19 however it should include zloylos/grsync#20
Related to #124

Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
wow, that was fast, very nice!

**Review by Itxaka — APPROVED** [review]

**Comment by davidcassany** [comment]
@Itxaka @mudler believe it or not, but now the situation is way worse... it always fail with the new grsync 😅 And it also fails on my local env. I am currently debugging it.

I think the grsync issue was worse than what I initially thought, probably the problem is that there is a goroutine waiting on `scanner.Scan()` for stdout and stderr, but it could happen that one of the two pipes (stdout and/or stderr) does not produce a single character, hence no EOF and it just blocks there... trying to validate it 🤔  I hope I did not break grsync with my PR 😓

**Comment by davidcassany** [comment]
Ok there were several issues here, first SyncData had a small issue while using the fs, the trailing `/` needs to be added after the convertion to the real fs. On the way I discovered the super ugly #135 😞  and that my fix of the grsync is not as good as I wanted, it can lead to infinite loops 😞 

Damn! Too many things at once to something that was supposed to be a low hanging fruit! 😭

**Comment by Itxaka** [comment]
should probably close this now that we have our own fork @davidcassany :)

**Comment by davidcassany** [comment]
Yes lets close this, no longer needed!

**Pull request closed without merging**
