### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by Itxaka**
Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
Looks good to me, is there any syntax or criteria to follow?
Can these docs be used to generate some nice web based docs?

**Comment by Itxaka** [comment]
Should appear in here: https://pkg.go.dev/github.com/rancher-sandbox/elemental-cli when its merged.

**Comment by Itxaka** [comment]
> Looks good to me, is there any syntax or criteria to follow?

https://go.dev/blog/godoc

**Comment by Itxaka** [comment]
will resend it, too much has changed

**Pull request closed without merging**
