### PR TITLE
Add OBS build files into the repository

### PR DESCRIPTION
**Pull request by davidcassany**
Part of rancher/elemental#577

Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

**Comment by davidcassany** [comment]
@Itxaka  looks like the secboot version we were using in go.mod is no longer available... I did an attempt to manually recreate the vendor folder without using the secboot fork but I miserably failed... I am worried we might be forced to keep around legacy code no longer available upstream, I am missing some background on this issue, do you have any idea about how should we proceed or workaround it?

**Review by kkaempf — APPROVED** [review]
Having the builder image Dockerfile here is a bit strange but I don't know a better place either :-/

**Comment by Itxaka** [comment]
> @Itxaka looks like the secboot version we were using in go.mod is no longer available... I did an attempt to manually recreate the vendor folder without using the secboot fork but I miserably failed... I am worried we might be forced to keep around legacy code no longer available upstream, I am missing some background on this issue, do you have any idea about how should we proceed or workaround it?

yikes...seems like they removed the fork that nullboot is using...weird, seeing that nullboot is still using that fork. Bit of a mess actually, because we dont want to recreate the whole thing ourselves....argh.

**Comment by Itxaka** [comment]
opened an issue upstream as it also happens in the nullboot repo: https://github.com/canonical/nullboot/issues/28

**Comment by davidcassany** [comment]
> Having the builder image Dockerfile here is a bit strange but I don't know a better place either :-/

We could keep it entirely within the OBS only, like the the `build-iso` image. However I do believe it makes sense it here. We call it the builder image, however it could also be called the `elemental-cli` image as this is what it actually includes and it makes sense for any `elemental build` command.

**Comment by Itxaka** [comment]
yikes, its a bit of a mess.

nullboot requires secboot which in turn requres go-tpm2. But all of those versions are a bit mangled and old. Updating them requires a chain of updates to the code in all three repos....we migth need to just implement  the parts that we are using from nullboot (list entry vars, remove entry, add entry) and call it a day, otherwise...I dont see a clear path in which we update 3 different libraries to be in sync, especially with all this TPM stuff in the middle, which we dont even care about here. Ugh.

**Pull request merged**
