### PR TITLE
Rework flags to unify some of them

### LINKED ISSUE #79: Move flags validaton to some generic place (`cmd/flags.go`?)
This to avoid having to duplicate flags checks incompatibilities like `--reboot` and `--poweroff` in all subcommands and reuse the logic.

In addition we could align which flags should be set from env_variables, config files and command line. For instance `--reboot` and `--poweroff` do not make much sense from a config file.

See https://github.com/rancher-sandbox/elemental/pull/72#discussion_r799453623

### PR DESCRIPTION
**Pull request by Itxaka**
Fixes #79 

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
Nice, looks good!

Just a couple of comments regarding further arrangements on flags.

What about binding `--reboot` and `--poweroff` (and probably others) manually? (I mean no config file)
Also `--directory` from reset and upgrade should be merged, `--directory` makes sense for the installer too (I think this is a miss from the former code, as this was only possible by using env vars so I missed it).

**Comment by Itxaka** [comment]
> What about binding --reboot and --poweroff (and probably others) manually? (I mean no config file)

Ummm I dont think its possible with our current setup. Anything that its on the files loaded that matches the Runconfig key will be unmarshalled there. We could make the keys in Runconfig be different so they dont match I guess? Like we could have Runconfig.PowerOffOnFinishTask so to match that from a config file it should have `poweroffonfinishtask: true` values in the config, but in the end it can be matched.

We could bind them to a local var instead and use that to set the value in the config directly if we dont want to expose it, i.e. :

```
var reboot bool 
upgradeCmd.Flags().BoolVar(&reboot, "--reboot", false, "")

```

But this means generating that `reboot` var in the root of the file so it can be accessed by the init and the Execute method, which is kind of bad. Also not sure if we can bind the flag in the Execute/PreRun methods 

We could also delay the command adding and use a function that does all of this stuff, and doesnt add itself to the root command. Instead on the root command you can that function that returns the cmd to add it to your root command. But that requires basically rewriting the whole cmd dir lol

Let me try if we are able to get the real flag value on Execute and bind it directly to the config value but Im not sure if that is possible at that point in time.

In any case, any reason for that? One of the cool things of the viper stuff its that you could have all your config directly on a config file, so no need for flags at all....not like we are using the config file anywhere lol

**Comment by davidcassany** [comment]
> In any case, any reason for that? One of the cool things of the viper stuff its that you could have all your config directly on a config file, so no need for flags at all....not like we are using the config file anywhere lol

I just thought that is kind a weird setting reboot on a config file, the same applies for the `--directory` flag, feels weird having it on a config file, those things are likely to be runtime and host dependent decisions. Anyway, you are right that this is additional flexibility. So probably we can assume mapping all flags to config values and keep it simple.

**Comment by Itxaka** [comment]
@davidcassany seems to work to override flags in the Execute methods so we can always ignore whatever is coming from the config and override the flag directly only with the flag value.

`cfg.Reboot, err = cmd.Flags().GetBool("reboot")` will override any values from the config or env and set the value passed via the flag.

**Comment by Itxaka** [comment]
We could also have a different struct for flag-only options and not bind that, only bind the config/flag/env options and then merge both together in the ReadConfigRun so we know which options can only be toggled from one or the other

**Comment by davidcassany** [comment]
> We could also have a different struct for flag-only options and not bind that, only bind the config/flag/env options and then merge both together in the ReadConfigRun so we know which options can only be toggled from one or the other

Yes that's also a good idea. I think this requires some more thinking about how to organize environment variables, config files and flags. Probably it could also make sense having a similar approach for env variables...

There's nothing wrong with the current implementation, just that it feels a bit messy. I guess this all related to #33 somehow, I have not a good/clear idea about how to do it though.

**Pull request merged**
